version: '3.4'

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 

  backend-api:
    image: backendapi
    build:
      context: .
      dockerfile: Services/Backend/Backend.API/Dockerfile
    depends_on:
      - sqldata

  webadmin:
    image: webadmin
    build:
      context: .
      dockerfile: Web/WebAdmin/Dockerfile
    depends_on:
      - backend-api

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Web/Frontend.MVC/Dockerfile
    depends_on:
      - backend-api