version: '3.4'

# Add a .env file with your custom environment variables
# BACKEND_API_KEY=TheMostSecureSecretOfAllT!me

services:

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433" # Important: In a production environment your should remove the external port
    volumes:
      - backend-sqldata:/var/opt/mssql

  backend-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${ESPACEROOM_BACKEND_AZURE_BACKEND_DB:-Server=sqldata;Database=EscapeRoom2021.Services.Backend;User Id=sa;Password=Pass@word}
      - BackendApiKey=${BACKEND_API_KEY}
    ports:
      - "13080:80" # Important: In a production environment your should remove the external port
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  webadmin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - BackendUrl=http://backend-api:80
      - BackendApiKey=${BACKEND_API_KEY}
    ports:
      - "13081:80" # Important: In a production environment your should remove the external port

  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - BackendUrl=http://backend-api:80
      - BackendApiKey=${BACKEND_API_KEY}
    ports:
      - "13082:80" # Important: In a production environment your should remove the external port

volumes:
  backend-sqldata:
    external: false